version: 0.2

phases:
    install:
        commands:
            - pip install Pygments
            - wget https://github.com/gohugoio/hugo/releases/download/v0.99.1/hugo_0.99.1_Linux-64bit.deb
            - dpkg -i hugo_0.99.1_Linux-64bit.deb
    build:
        commands:
            - hugo
            - echo "S3 Upload Beginning"
            - aws s3 sync public/ s3://moski.me/ --region eu-west-1 --delete --sse AES256
            - echo "S3 Upload Complete"
    post_build:
        commands:
            - aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --paths "/*"
            - echo "Build complete"
